proxies:
  - name: "CodespaceProxy"
    type: socks5
    server: 127.0.0.1
    port: 10351

proxy-groups:
  - name: "Global"
    type: select
    proxies:
      - CodespaceProxy

rules:
  - GEOSITE,CN,DIRECT
  - MATCH,Global
  